// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tdaosoupsxmrextxdqbn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRkYW9zb3Vwc3htcmV4dHhkcWJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY4NDAyODksImV4cCI6MjA2MjQxNjI4OX0._v5UbmZqKHxG1WA2IN7OE2gLvrIImGWmCkvyGFDZMtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);